// <auto-generated />
using System;
using ExpiryTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpiryTrack.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926194041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ExpiryTrack.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("FinanceReviewThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("RequiresFinancialReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WarningPeriodDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categories_FinanceReviewThreshold", "FinanceReviewThreshold IS NULL OR FinanceReviewThreshold >= 0");

                            t.HasCheckConstraint("CK_Categories_WarningPeriodDays", "WarningPeriodDays BETWEEN 1 AND 365");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RequestId");

                    b.HasIndex("StoredFileName")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_Documents_Owner", "(ItemId IS NULL) <> (RequestId IS NULL)");

                            t.HasCheckConstraint("CK_Documents_Size", "SizeBytes > 0 AND SizeBytes <= 10485760");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CurrentPeriodId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Provider")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ResponsibleUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StateChangedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrentPeriodId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("Items", null, t =>
                        {
                            t.HasCheckConstraint("CK_Items_LifecycleState", "LifecycleState IN ('Active','ExpiringSoon','Expired','Cancelled')");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.ItemStateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FromState")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemStateHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItemStateHistory_FromState", "FromState IN ('Active','ExpiringSoon','Expired','Cancelled')");

                            t.HasCheckConstraint("CK_ItemStateHistory_ToState", "ToState IN ('Active','ExpiringSoon','Expired','Cancelled')");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.LifecyclePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedFromRequestId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedFromRequestId")
                        .IsUnique();

                    b.HasIndex("ItemId", "PeriodNumber")
                        .IsUnique();

                    b.ToTable("LifecyclePeriods", null, t =>
                        {
                            t.HasCheckConstraint("CK_LifecyclePeriods_Cost", "Cost IS NULL OR Cost > 0");

                            t.HasCheckConstraint("CK_LifecyclePeriods_Dates", "ExpirationDate > StartDate");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("Notifications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Notifications_Link", "ItemId IS NULL OR RequestId IS NULL");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.RenewalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsFinancialReview")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProposedCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateOnly>("ProposedExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("RequestedByUserId");

                    b.ToTable("RenewalRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_RenewalRequests_ProposedCost", "ProposedCost IS NULL OR ProposedCost > 0");

                            t.HasCheckConstraint("CK_RenewalRequests_Status", "Status IN ('PendingFinancialReview','PendingManagerApproval','ClarificationRequired','Approved','Rejected','Completed')");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.RequestAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FinancialRecommendation")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestActions", null, t =>
                        {
                            t.HasCheckConstraint("CK_RequestActions_ActionType", "ActionType IN ('Submitted','FinanceReviewed','ClarificationRequested','ClarificationProvided','Approved','Rejected','Completed','ClosedByExpiry')");

                            t.HasCheckConstraint("CK_RequestActions_FinancialRecommendation", "FinancialRecommendation IN ('Approve','Reject')");

                            t.HasCheckConstraint("CK_RequestActions_FromStatus", "FromStatus IN ('PendingFinancialReview','PendingManagerApproval','ClarificationRequired','Approved','Rejected','Completed')");

                            t.HasCheckConstraint("CK_RequestActions_ToStatus", "ToStatus IN ('PendingFinancialReview','PendingManagerApproval','ClarificationRequired','Approved','Rejected','Completed')");
                        });
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Department", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.User", "Manager")
                        .WithOne("ManagedDepartment")
                        .HasForeignKey("ExpiryTrack.Api.Models.Department", "ManagerId");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Document", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.Item", "Item")
                        .WithMany("Documents")
                        .HasForeignKey("ItemId");

                    b.HasOne("ExpiryTrack.Api.Models.RenewalRequest", "Request")
                        .WithMany("Documents")
                        .HasForeignKey("RequestId");

                    b.HasOne("ExpiryTrack.Api.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Request");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Item", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpiryTrack.Api.Models.LifecyclePeriod", "CurrentPeriod")
                        .WithOne()
                        .HasForeignKey("ExpiryTrack.Api.Models.Item", "CurrentPeriodId");

                    b.HasOne("ExpiryTrack.Api.Models.Department", "Department")
                        .WithMany("Items")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpiryTrack.Api.Models.User", "ResponsibleUser")
                        .WithMany("ResponsibleItems")
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CurrentPeriod");

                    b.Navigation("Department");

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.ItemStateHistory", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId");

                    b.HasOne("ExpiryTrack.Api.Models.Item", "Item")
                        .WithMany("StateHistory")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.LifecyclePeriod", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.RenewalRequest", "CreatedFromRequest")
                        .WithOne("CreatedPeriod")
                        .HasForeignKey("ExpiryTrack.Api.Models.LifecyclePeriod", "CreatedFromRequestId");

                    b.HasOne("ExpiryTrack.Api.Models.Item", "Item")
                        .WithMany("Periods")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedFromRequest");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Notification", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("ExpiryTrack.Api.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpiryTrack.Api.Models.RenewalRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("Item");

                    b.Navigation("RecipientUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.RenewalRequest", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.LifecyclePeriod", "Period")
                        .WithMany("RenewalRequests")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExpiryTrack.Api.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.RequestAction", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId");

                    b.HasOne("ExpiryTrack.Api.Models.RenewalRequest", "Request")
                        .WithMany("Actions")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.User", b =>
                {
                    b.HasOne("ExpiryTrack.Api.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ExpiryTrack.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Department", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Item", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Periods");

                    b.Navigation("StateHistory");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.LifecyclePeriod", b =>
                {
                    b.Navigation("RenewalRequests");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.RenewalRequest", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("CreatedPeriod");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ExpiryTrack.Api.Models.User", b =>
                {
                    b.Navigation("ManagedDepartment");

                    b.Navigation("ResponsibleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
